#!/usr/bin/env bash
# install Nginx on Ubuntu and set basic configurations
# Variables
NGINX_CONF="/etc/nginx/sites-available/default"
BACKUP_FILE="/var/www/html/index.nginx-debian.html.bckp"
INDEX_FILE="/var/www/html/index.nginx-debian.html"
LOG_FILE="/var/log/nginx_install.log"

# Update package index and install Nginx
sudo apt-get update -y >> $LOG_FILE 2>&1 && \
sudo apt-get install nginx -y >> $LOG_FILE 2>&1 && \

# Start Nginx service
sudo service nginx start >> $LOG_FILE 2>&1 && \

# Allow HTTP traffic through firewall
sudo ufw allow 'Nginx HTTP' >> $LOG_FILE 2>&1 && \

# Change ownership and permissions for web root directory
sudo chown -R "$USER":"$USER" /var/www/html && \
sudo chmod -R 755 /var/www/html && \

# Backup the default Nginx index file and replace with "Hello World!"
cp $INDEX_FILE $BACKUP_FILE && \
echo "Hello World!" | sudo tee $INDEX_FILE > /dev/null && \

# Restart Nginx
if pgrep -x "nginx" > /dev/null
then
    echo "Nginx is running. Restarting..."
    sudo service nginx restart >> $LOG_FILE 2>&1
else
    echo "Nginx is not running. Starting..."
    sudo service nginx start >> $LOG_FILE 2>&1
fi

echo "Nginx installed and configured. Log file: $LOG_FILE"
