#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

# Update package index and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Define HAProxy configuration file
haproxy_config="/etc/haproxy/haproxy.cfg"

# Configure HAProxy
sudo tee $haproxy_config > /dev/null <<EOF
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

frontend besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
        timeout client 30s
        timeout connect 5s
        timeout server 30s

backend besthor_backend
        mode http
        balance roundrobin
        server 522977-web-01 54.84.254.93:80 check
        server 522977-web-02 34.229.71.191:80 check
        timeout client 30s
        timeout connect 5s
        timeout server 30s
EOF

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Test HAProxy configuration
sudo haproxy -c -f $haproxy_config

# Restart HAProxy service
sudo systemctl restart haproxy

echo "HAProxy installed, configured, and restarted successfully."
