#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

set -e

# Update package index and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Define HAProxy configuration
haproxy_config="/etc/haproxy/haproxy.cfg"
haproxy_frontend="besthor_frontend"
haproxy_backend="besthor_backend"
haproxy_servers=(
    "server 522977-web-01 54.84.254.93:80 check"
    "server 522977-web-02 34.229.71.191:80 check"
)

# Configure HAProxy
sudo tee $haproxy_config > /dev/null <<EOF
frontend $haproxy_frontend
    bind *:80
    mode http
    default_backend $haproxy_backend

backend $haproxy_backend
    balance roundrobin
    ${haproxy_servers[@]}
EOF

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Test HAProxy configuration
sudo haproxy -c -f $haproxy_config

# Restart HAProxy service
sudo systemctl restart haproxy.service

echo "HAProxy installed, configured, and restarted successfully."
