#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
hr=0
while ((hr < 13))
do
    echo "Hour: $hr"
    mins=1
    while ((mins < 60))
    do
        echo $mins
        ((mins++))
    done
    ((hr++))
done