#!/usr/bin/env bash
#This script displays:
#The content of the current directory In a list format
#Where only the part of the name after the first dash is displayed
content=$(ls)
for i in $content
do
    echo "$i" | cut -d "-" -f2
done